# File: .github/workflows/repo-sync.yml

on:
  push:
    branches:
      - chinese
  schedule:
  - cron:  '30 5,18 * * *'
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout branch chinesepod"
      uses: actions/checkout@v3
      with:
          ref: chinesepod
    - name: "Repo-sync branch chinesepod"
      uses: repo-sync/github-sync@v2
      with:
          source_repo: "https://github.com/CeciliaBot/CeciliaBot.github.io.git"
          source_branch: master
          destination_branch: chinesepod
          github_token: ${{ secrets.PAT }}
    - name: "Patch-frontend branch chinese"
      run: |
              git reset --hard origin/chinesepod
              git config --global user.email ${{ secrets.EMAIL }}
              git config --global user.name ${{ secrets.USERNAME }}
              git config --global user.password ${{ secrets.PAT }}
              wget https://cdn.glitch.com/5c21c869-ea9a-48ba-b019-90cd493f45cd%2Fcamp-fire-icon%20small.png\?v\=1585067234171 -O ./img/camp-fire.png
              wget https://cdn.glitch.com/5c21c869-ea9a-48ba-b019-90cd493f45cd%2Fangienobg.gif?v=1585008523656 -O ./img/calcul.gif
              find ./ -type f -exec sed -i -e 's#https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js#https://cdnjs.loli.net/ajax/libs/jquery/3.5.1/jquery.min.js#g' {} \; 
              find ./ -type f -exec sed -i -e 's#https://cdn.jsdelivr.net/npm/js-combinatorics@0.5.5/combinatorics.min.js#https://cdnjs.loli.net/ajax/libs/js-combinatorics/0.5.5/combinatorics.min.js#g' {} \; 
              find ./ -type f -exec sed -i -e 's#https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.min.js#https://cdnjs.loli.net/ajax/libs/vue/2.6.13/vue.min.js#g' {} \; 
              find ./ -type f -exec sed -i -e 's#https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.1/css/all.min.css#https://cdnjs.loli.net/ajax/libs/font-awesome/5.13.1/css/all.min.css#g' {} \;
              find ./ -type f -exec sed -i -e 's#<script defer src="https://www.googletagmanager.com/gtag/js?id=UA-161715700-1"></script>#<script async src="https://um.iwarship.cn/shipdata" data-website-id="30f2812b-900e-4265-9dfa-cddfdeb04360"></script>#g' {} \;
              find ./ -type f -exec sed -i -e 's#<img src="https://cdn.glitch.com/5c21c869-ea9a-48ba-b019-90cd493f45cd%2Fcamp-fire-icon%20small.png?v=1585067234171" alt="calculate" style="margin-bottom: -10px; height: 40px;" />#<img src="./img/camp-fire.png" alt="calculate" style="margin-bottom: -10px; height: 40px;" />#g' {} \;
              find ./ -type f -exec sed -i -e 's#<img src="https://cdn.glitch.com/5c21c869-ea9a-48ba-b019-90cd493f45cd%2Fangienobg.gif?v=1585008523656" style="height:100px"/>#<img src="./img/calcul.gif" style="height:100px"/>#g' {} \;
              git add ./*
              git commit -m "Patch frontend urls"
              git push
       
      
   
    
